[package]
name = "fts"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.1"
rust-stemmers = "1.2.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false